name:                V1Acc
version:             0.1.0.0
github:              "githubuser/V1Acc"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/V1Acc#readme>

dependencies:
- base >= 4.7 && < 5
- accelerate
- accelerate-io
- accelerate-llvm
- accelerate-llvm-native
- accelerate-llvm-ptx
- deepseq
- lens-accelerate
- mtl
- mwc-random-accelerate
- accelerate-blas
- lens
- spool
- vector
- bytestring
- random-fu
- random-source
- time


library:
  source-dirs: src
  ghc-options:
    - -O2

executables:
  V1Acc-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -O2
    - -with-rtsopts=-N
    - -with-rtsopts=-n2M
    - -with-rtsopts=-A64M
    dependencies:
    - V1Acc

tests:
  V1Acc-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - V1Acc
    - tasty
    - tasty-hunit
